language: python

cache: pip

services:
- postgresql

python:
- '3.5'
- '3.6'
- 'nightly'  # currently 3.7

env:
# TODO change when 3 is released
- 'AIOHTTP_VERSION=aiohttp==3.2.1'  # WARNING: if you change this, change it in deploy too
- 'AIOHTTP_VERSION=https://github.com/aio-libs/aiohttp/archive/master.zip'

matrix:
  allow_failures:
  - python: 'nightly'
  - env: 'AIOHTTP_VERSION=https://github.com/aio-libs/aiohttp/archive/master.zip'

install:
- make install
- pip install -U "${AIOHTTP_VERSION}"
- pip freeze

script:
- make lint
- make test
- ./tests/check_tag.py
#- make docs
- pip freeze
- ls -lha

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: samuelcolvin
  password:
    secure: "u82o1Ny1Xic5OdJYFHBmuJCISYc7tXr09SzjYxz0HVjIyMYo+mTOy5Eex2OVHenOHQNmGhABYTXdvt3Q6x1VN8hgtRFQhMAIbtmu5hYOLkSznfHc+0sDZV3UqbQzALuceHyVjnG/+JZwJCQisOibYiQ7ywevx7EDtuSS+YAZor4eLSMbm2Gole/jAcDvoxs+JkPxk7VuezK5DJq/6uWwc+IWrN24XSwN+FJ4WwFAmkB1YQOGDe4T0zoMtm5MzW4j51P5uvjIUtUVQbhUbdKiilM8QvYN5x1HLzrnl9Ye2OPYSX+T+4jx+9cuX+S4bBDielx41jrDb4q8sYf9lrW4uHF4Wqz4Zi++2J73gk5kv6RC0IiWjKrrRk75CoJMZZr7LYce/nOg2e7bbsJf6NpbeFnAdScF1vmAo/qVYRUMTABXALHyiJQqCqRs0kUt1Rja10YMlKOGn2a7+CMm0QJGDJCVIs1WPL1nIv98sHTaB14TG1/syQM+Whj+iEaU5WQpN0L6dpt7Cl5ZdafEjcumHM6bKg6CDftOdxTnZNMVhoSiEJN6+0k6QM7rBInQvOWjRiz6ZBIK+LVwGbfCB3eOqVd+1Cphtp6137RZ0qtQFKlVV0ANyHdRGqD3jdVKulZK5+8x1Hon3azn5PQlsF+kK1e3YyCatiqQk//tgaPqeFc="
  distributions: sdist bdist_wheel
  # skip_cleanup: true is required to include livereload.js
  skip_cleanup: true
  on:
    tags: true
    python: 3.6
    condition: "$AIOHTTP_VERSION = aiohttp==3.2.1"
